### PR TITLE
adds minimum pyproject file

### PR DESCRIPTION
**Pull request by gsilvapt**
## Description
Adds `pyproject.toml` file as per #24 . 

You don't have documentation on how to build it and I was unsure whether we would prefer to keep that to a `CONTRIBUTE.md` file or something similar.

## Motivation and Context
Solves typical dist utils bottlenecks - hopefully.

## How Has This Been Tested?
Fresh new virtualenv, installed `pep517` with `pip install pep517`, created `pyproject.toml`, ran `python -m pep517.build .` and successfully built binaries in `dist/` directory.

Followed [this blog post](https://hynek.me/articles/sharing-your-labor-of-love-pypi-quick-and-dirty/) as it was the only content capable of making me understand the build system with pyproject. I've only used it, so far, to configure black 😅 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by gsilvapt** [comment]
Can you guys help me review this one, please? I ran most of the checks locally and it seems that the conflicting files are not the one I added here, but other files, like the README and a hook. At least that's the output I'm getting locally. The one we got in the actions is not very clear what files or where the errors occur.

**Comment by Ambro17** [comment]
Hello @gsilvapt, i tried Code Analysis from github and i merged a new file that was not adhering to pre-commit style. If you merge master to your branch you should stop seeint that error.

**Comment by gsilvapt** [comment]
> Hello @gsilvapt, i tried Code Analysis from github and i merged a new file that was not adhering to pre-commit style. If you merge master to your branch you should stop seeint that error.

Ahh, thanks. Updated the ref then.

**Comment by Ambro17** [comment]
Thank you @gsilvapt for your second contribution! You rock!

May i ask why is the minimum version on setuptools required? I looked at the [changelog](https://setuptools.readthedocs.io/en/latest/history.html#v40-0-0) but didn't find a hint on why would that could be

**Comment by gsilvapt** [comment]
Thank you guys. This project helps making slack apps easy and nowadays
that's a big plus. Giving back to something I used for free 👍

Regarding the version, no particular reason. I think you can even drop the
version altogether and just let it be.

**Comment by Ambro17** [comment]
I will leave the version and change only when we discover an incompatibility.

**Pull request merged**
